version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: order_date
        tests:
          - not_null

  - name: stg_order_items
    columns:
        - name: order_item_id
          tests:
            - not_null
            - unique
        - name: order_id
          tests:
            - not_null
        - name: product_id
          tests:
            - not_null

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
  - name: stg_products 
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
  - name: stg_addresses 
    columns:
      - name: address_id
        tests:
          - not_null
          - unique