version: 2

models:
  - name: fact_orders
    columns:
      - name: order_id
        tests:
          - not_null
      - name: customer_id
        tests:
           - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: product_id
        tests:
          - relationships:
              to: ref('dim_products')
              field: product_id
      - name: order_date_key
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: line_item_total
        tests:
          - line_item_calculation:
              model_name: ref('fact_orders')
              column_name: line_item_total

  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: dim_products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

  - name: dim_date
    columns:
        - name: date_key
          tests:
            - not_null
            - unique